version: "3"
virtualbrowsers:
- name: local-prefect-server
  url: http://127.0.0.1:8006
virtualmachines:
- name: prefect-sandbox
  image: ubuntu-os-cloud/ubuntu-2404-noble-amd64-v20241004
  memory: 4096
  cpus: 1
