#!/bin/bash
set -euxo pipefail

cd /root/pal

cat <<'EOF' > interactive_and_concurrent.py
import time

from prefect import flow, pause_flow_run, task
from prefect.futures import wait
from prefect.task_runners import ThreadPoolTaskRunner


@flow(log_prints=True)
def greet_user():
    user = pause_flow_run(wait_for_input=str)
    print(f"Hello, {user}!")


@task
def stop_at_floor(floor: int):
    print(f"elevator moving to floor {floor}")
    time.sleep(floor)
    print(f"elevator stops on floor {floor}")


@flow(task_runner=ThreadPoolTaskRunner(max_workers=2), log_prints=True)
def elevator():
    futures = []
    for floor in range(3, 0, -1):
        futures.append(stop_at_floor.submit(floor))
    wait(futures)


if __name__ == "__main__":
    elevator()
EOF
